version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: react.Dockerfile
    ports:
      - "5173:5173"  

  backend:
    build:
      context: .
      dockerfile: flask.Dockerfile  
    ports:
      - "5001:5001"  
